version: '3'
services:
  web:
    build: .
    ports:
    - "8890:8891"
    volumes:
    - .:/code
    - logvolume01:/var/log
    links:
    - redis
  redis:
    image: redis
volumes:
  logvolume01: {}
  